### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by YangtseSu** [fujiwarat/ibus-xkb#1]
/usr/bin/vapigen --metadatadir ../../ui/gtk3 --library gkbd \
    --pkg gtk+-3.0 --pkg glib-2.0 --pkg gmodule-2.0 \
    /usr/share/gir-1.0/Gkbd-3.0.gir
Xkl-1.0.gir:891.51-891.51: error: The type name `X.XEvent' could not be found
            <type name="xlib.XEvent" c:type="XEvent*"/>
                                                  ^
Generation failed: 1 error(s), 0 warning(s)

**Comment by fujiwarat** [comment]
> /usr/bin/vapigen --metadatadir ../../ui/gtk3

Does your ../../ui/gtk3 have Xkl-1.0.metadata ?

**Comment by YangtseSu** [comment]
no,it's in vala

**Comment by fujiwarat** [comment]
No?
I'm saying Xkl-1.0.metadata is included in ibus-xkb tarball.

**Comment by YangtseSu** [comment]
So,the git version could not build.

**Comment by fujiwarat** [comment]
> no,it's in vala

OK, you meant bindings/vala
Thanks.

**Comment by fujiwarat** [comment]
I updated bindings/vala/Makefile.am. Please check out the git again.
If you already have the git:

% git reset --hard HEAD^^^^^
% git pull

--- a/bindings/vala/Makefile.am
+++ b/bindings/vala/Makefile.am
@@ -51,7 +51,7 @@ ibus-xkb-@IBUS_XKB_API_VERSION@.vapi: $(vapi_deps)

 if ENABLE_LIBGNOMEKBD
 $(builddir)/gkbd.vapi:
-   $(VAPIGEN) --metadatadir $(top_srcdir)/ui/gtk3 --library gkbd \
-   $(VAPIGEN) --metadatadir $(srcdir) --library gkbd \
      --pkg gtk+-3.0 --pkg glib-2.0 --pkg gmodule-2.0 \
      /usr/share/gir-1.0/Gkbd-3.0.gir
  $(NULL)
